services:
  scylladb:
    user: root
    container_name: scylladb
    image: scylladb/scylla:6.0
    ports:
      - 9042:9042
    volumes:
      - type: volume
        source: scylladb
        target: /var/lib/scylla
        volume:
          nocopy: true
    networks:
      - websocket-chat-service

  redis:
    user: root
    image: bitnami/redis:7.4.0
    container_name: redis
    ports:
      - 6379:6379
    environment:
      REDIS_DATABASE: ${REDIS_DATABASE:?error}
      REDIS_PASSWORD: ${REDIS_PASSWORD:?error}
    volumes:
      - /redis-data:/bitnami/redis/data
    networks:
      - websocket-chat-service

  redisinsight:
    user: root
    image: redis/redisinsight:2.56
    ports:
      - 5540:5540
    volumes:
      - /redisinsight-data:/data
    networks:
      - websocket-chat-service

volumes:
  scylladb:

networks:
  websocket-chat-service:
    driver: bridge